config/routes.rb
BankOfMd::Application.routes.draw do

  root :to => 'home#index'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/overview' => 'overview#index'

  get '/profile/new' => 'users#new'
  post '/profile/new' => 'users#create'
  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit'
  put '/profile/edit' => 'users#update'


  get '/family' => 'family#index'
  get '/family/exists' => 'family#exists'
  get '/family/new' => 'family#new'
  post '/family/new' => 'family#create'
  get '/family/edit' => 'family#edit'
  put '/family/edit' => 'family#update'

  get '/chores' => 'chores#index'
  get '/chores/new' => 'chores#new'
  post '/chores/new' => 'chores#create'
  get '/chores/edit' => 'chores#edit'
  put '/chores/edit' => 'chores#update'

  get '/accounts' => 'accounts#index'
  get '/accounts/new' => 'accounts#new'
  post '/accounts/new' => 'accounts#create'
  get '/accounts/edit' => 'accounts#edit'
  put '/accounts/edit' => 'accounts#update'
  get '/accounts/start' => 'accounts#start'
  post '/accounts/start' => 'accounts#start_create'

  get '/transactions' => 'transactions#new'
  post '/transactions' => 'transactions#create'
  get '/transactions/edit' => 'transactions#edit'
  put '/transactions/edit' => 'transactions#update'
  get '/transactions/account' => 'transactions#account'
  post '/transactions/account' => 'transactions#account_create'

  get '/allowances/start' => 'allowances#start'
  post '/allowances/start' => 'allowances#start_create'

end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController

  def index
    @accounts = @auth.family.accounts if @auth.family.accounts != nil
    @children = @auth.family.members.where(:is_parent => 'false') if @auth.family != nil
    @transactions = @auth.family.transactions
  end

end

app/views/overview/_child_accounts.html.erb
<div class="four columns">
  <div class="acct_box">

    <div class="acct_child">
      <%= child.first_name %>
    </div><!-- .acct_child -->

      <div class="five columns acct_headers">Account</div>
      <div class="seven columns acct_headers">Balance</div>

      <% @accounts.each do |account| %>
        <% if account.child_id == child.id %>
          <div class="acct_row twelve columns">
            <div class="acct_name five columns acct_col acct_data"><%= account.name %></div><!-- .acct_name -->
            <div class="acct_balance five columns acct_col acct_data"><%= account.balance %></div><!-- .acct_balance -->
            <div class="acct_trans one column acct_col acct_data"><%= link_to '+', transactions_account_path(:account_id => account.id, :is_credit => true) %></div><!-- .acct_credit -->
            <div class="acct_trans one column acct_col acct_data"><%= link_to '-', transactions_account_path(:account_id => account.id, :is_credit => false) %></div><!-- .acct_debit -->
          </div><!-- .acct_row .twelve.columns-->
        <% end %>
      <% end %>

  </div><!-- .acct_box -->
</div><!-- .four.columns -->

app/views/overview/_transactions.html.erb
<div class="one column trans_data"><%= transactions.created_at.strftime("%m/%d") %></div>
<div class="one column trans_data"><%= transactions.account.child.first_name %></div>
<div class="two columns trans_data"><%= transactions.account.name %></div>
<div class="four columns trans_data"><%= transactions.description %></div>
<div class="two columns trans_data"><%= "+" if transactions.is_credit == "true" %><%= "-" if transactions.is_credit == "false" %><%= transactions.amt_change %></div>
<div class="two columns trans_data"><%= transactions.end_balance %></div>

app/views/overview/index.html.erb
<div class="twelve columns title">
  Accounts<span class="add"><%= link_to "Add", accounts_new_path %></span>
</div><!-- .twelve.columns -->

<div class="twelve columns">
  <%= render :partial => 'child_accounts', :collection => @children, :as => :child %>
</div><!-- .twelve.columns -->

<div class="twelve columns title">
  Recent Transactions
</div><!-- .twelve.columns -->

<div class="twelve columns">
  <div class="one column trans_headers">Date</div>
  <div class="one column trans_headers">Child</div>
  <div class="two columns trans_headers">Account</div>
  <div class="four columns trans_headers">Description</div>
  <div class="two columns trans_headers">Amount</div>
  <div class="two columns trans_headers">Balance</div>
</div><!-- .twelve.columns -->

<div class="twelve columns">
  <%= render :partial => 'transactions', :collection => @transactions, :as => :transactions %>
</div><!-- .twelve.columns -->