config/routes.rb
BankOfMd::Application.routes.draw do

  root :to => 'home#index'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/overview' => 'overview#index'

  get '/profile/new' => 'users#new'
  post '/profile/new' => 'users#create'
  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit'
  put '/profile/edit' => 'users#update'


  get '/family' => 'family#index'
  get '/family/exists' => 'family#exists'
  get '/family/new' => 'family#new'
  post '/family/new' => 'family#create'
  get '/family/edit' => 'family#edit'
  put '/family/edit' => 'family#update'

  get '/chores' => 'chores#index'
  get '/chores/new' => 'chores#new'
  post '/chores/new' => 'chores#create'
  get '/chores/edit' => 'chores#edit'
  put '/chores/edit' => 'chores#update'

  get '/accounts' => 'accounts#index'
  get '/accounts/new' => 'accounts#new'
  post '/accounts/new' => 'accounts#create'
  get '/accounts/edit' => 'accounts#edit'
  put '/accounts/edit' => 'accounts#update'
  get '/accounts/start' => 'accounts#start'
  post '/accounts/start' => 'accounts#start_create'

  get '/transactions' => 'transactions#new'
  post '/transactions' => 'transactions#create'
  get '/transactions/edit' => 'transactions#edit'
  put '/transactions/edit' => 'transactions#update'
  get '/transactions/account' => 'transactions#account'
  post '/transactions/account' => 'transactions#account_create'

  get '/allowances/start' => 'allowances#start'
  post '/allowances/start' => 'allowances#start_create'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  last_name       :string(255)
#  first_name      :string(255)
#  email           :string(255)
#  text_number     :string(255)
#  is_parent       :boolean
#  family_id       :integer
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  belongs_to :family
  has_many :transactions
  has_many :accounts, :class_name => 'Account', :foreign_key => 'child_id'
  has_many :chores_assigned, :class_name => 'Chore', :foreign_key => 'parent_id'
  has_many :chores, :class_name => 'Chore', :foreign_key => 'child_id'
  has_many :transactions_created, :class_name => 'Transaction', :foreign_key => 'parent_id'
  has_many :transactions, :class_name => 'Transaction', :foreign_key => 'child_id'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(params[:new_user])
    if user.save
      family = @auth.family
      family.members << user
    end

    if user.is_parent == 't'
      redirect_to family_path
    else
      session[:new_user_id] = user.id
      redirect_to accounts_start_path
    end

  end

  def edit
  end

  def show
    @parents = @auth.family.members.where(:is_parent => 'true') if @auth.family != nil
    @children = @auth.family.members.where(:is_parent => 'false') if @auth.family != nil

    if params[:id]
      @profile = User.find(params[:id])
    else
      @profile = @auth
    end
  end

  def update
    if @auth.update_attributes(params[:user])
      redirect_to profile_path
    else
      render :edit
    end
  end

  private
  def ensure_logged_in
    redirect_to root_path if @auth.nil?
  end

end

app/views/users/_form.html.erb
  <%= form_tag do %>

    <div class='field'>
      <%= label_tag 'First Name:' %>
      <%= text_field_tag 'new_user[first_name]' %>
    </div>

    <div class='field'>
      <%= label_tag 'Last name:' %>
      <%= text_field_tag 'new_user[last_name]' %>
    </div>

    <div class="field">
      <%= radio_button_tag 'new_user[is_parent]', 'true' %> Parent
      <%= radio_button_tag 'new_user[is_parent]', 'false' %> Child
  </div>

    <div class='field'>
      <%= label_tag 'Email:' %>
      <%= text_field_tag 'new_user[email]' %>
    </div>

    <div class='field'>
      <%= label_tag 'Text Number (optional):' %>
      <%= text_field_tag 'new_user[text_number]' %>
    </div>

    <div class='field'>
      <%= label_tag 'Password:' %>
      <%= password_field_tag 'new_user[password]' %>
    </div>

    <div class='field'>
      <%= label_tag 'Confirmation:' %>
      <%= password_field_tag 'new_user[password_confirmation]'%>
    </div>

    <div class='field'>
      <%= submit_tag "Submit", :class => "secondary button" %>
    </div>

  <% end %>

app/views/users/_members.html.erb
  <div class='family_member'><%= member.first_name %> <%= member.last_name%> </div>

app/views/users/_user.html.erb
<div class='profile'>
  <h1><%= profile.first_name %> <%= profile.last_name %> <%= link_to 'edit', profile_edit_path  %> </h1>
  <ul>
    <li><%= profile.email %></li>
    <li><%= profile.text_number %></li>
  </ul>
</div>

app/views/users/edit.html.erb
<div class="forms">

  <div class="title">Edit User</div>

  <%= form_for @auth, :url => '/profile/edit' do |f| %>

    <div class='field'>
      <%= label_tag 'First Name:' %>
      <%= f.text_field 'first_name' %>
    </div>

    <div class='field'>
      <%= label_tag 'Last name:' %>
      <%= f.text_field 'last_name' %>
    </div>

    <div class='field'>
      <%= label_tag 'Email:' %>
      <%= f.text_field 'email' %>
    </div>

    <div class='field'>
      <%= label_tag 'Text Number (optional):' %>
      <%= f.text_field 'text_number' %>
    </div>

    <div class='field'>
      <%= label_tag 'Password:' %>
      <%= f.password_field 'password' %>
    </div>

    <div class='field'>
      <%= label_tag 'Confirmation:' %>
      <%= f.password_field 'password_confirmation'%>
    </div>

    <div class='field'>
      <%= f.submit %>
    </div>

  <% end %>

</div><!-- .forms -->

app/views/users/index.html.erb
Profile index page

app/views/users/new.html.erb
<div class="forms">

  <div class="title">New User</div>

  <%= render :partial => 'form' %>

</div><!-- .forms -->

app/views/users/show.html.erb
<div class="title">Profile<span class="edit"><%= link_to 'edit', profile_edit_path %></span></div>

<div class="profile_row"><span class="profile_category">Name:</span> <span class="profile_data"><%= @auth.first_name %> <%= @auth.last_name %></span></div>
<div class="profile_row"><span class="profile_category">Family:</span> <span class="profile_data"><%= @auth.family.name %></span></div>
<div class="profile_row"><span class="profile_category">Email:</span> <span class="profile_data"><%= @auth.email %></span></div>
<div class="profile_row"><span class="profile_category">Text number:</span> <span class="profile_data"><%= @auth.text_number %></span></div>

<div class="title">Family <span class="add"><%= link_to 'Add member', family_exists_path %></span></div>

<div class="family_category">
  <div class="family_title">Parents</div>
  <%= render :partial => 'members', :collection => @parents, :as => :member %>
</div><!-- .family_category -->

<div class="family_category">
  <div class="family_title">Children</div>
  <%= render :partial => 'members', :collection => @children, :as => :member  %>
</div><!-- .family_category -->

<div class="clearfix"></div>