config/routes.rb
BankOfMd::Application.routes.draw do

  root :to => 'home#index'

  get '/register' => 'register#new'
  post '/register' => 'register#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

  get '/overview' => 'overview#index'

  get '/profile/new' => 'users#new'
  post '/profile/new' => 'users#create'
  get '/profile' => 'users#show'
  get '/profile/edit' => 'users#edit'
  put '/profile/edit' => 'users#update'


  get '/family' => 'family#index'
  get '/family/exists' => 'family#exists'
  get '/family/new' => 'family#new'
  post '/family/new' => 'family#create'
  get '/family/edit' => 'family#edit'
  put '/family/edit' => 'family#update'

  get '/chores' => 'chores#index'
  get '/chores/new' => 'chores#new'
  post '/chores/new' => 'chores#create'
  get '/chores/edit' => 'chores#edit'
  put '/chores/edit' => 'chores#update'

  get '/accounts' => 'accounts#index'
  get '/accounts/new' => 'accounts#new'
  post '/accounts/new' => 'accounts#create'
  get '/accounts/edit' => 'accounts#edit'
  put '/accounts/edit' => 'accounts#update'
  get '/accounts/start' => 'accounts#start'
  post '/accounts/start' => 'accounts#start_create'

  get '/transactions' => 'transactions#new'
  post '/transactions' => 'transactions#create'
  get '/transactions/edit' => 'transactions#edit'
  put '/transactions/edit' => 'transactions#update'
  get '/transactions/account' => 'transactions#account'
  post '/transactions/account' => 'transactions#account_create'

  get '/allowances/start' => 'allowances#start'
  post '/allowances/start' => 'allowances#start_create'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/views/home/index.html.erb
<div class="row">
  <div class="nine columns">
    <div id="featured">
        <%= image_tag("home_featured_1.jpg") %>
        <%= image_tag("home_featured_3.jpg") %>
        <%= image_tag("home_featured_2.jpg") %>
        <%= image_tag("home_featured_4.jpg") %>
    </div><!-- #featured -->
  </div><!-- .nine.columns #featured -->

  <div class="three columns">
    <div id="home_box1">
      <p><strong>Bank of Mom & Dad</strong> is a chore organizer and virtual bank. It helps parents keep track of their children's chores, administer allowances, and manage credit/debit transactions.</p> <p>Help your children reach their financial goals and march towards independence by teaching them good banking habits in a realistic environment.</p>
    </div><!-- #home_box1 -->
    <div id="home_box2">
      <%= link_to("Register Now!", register_path) %>
    </div><!-- #home_box2 -->
  </div><!-- .three.columns -->

<div class="clearfix"></div>


<script type="text/javascript">
   $(window).load(function() {
       $("#featured").orbit({
  advanceSpeed: 3500,
  animationSpeed: 500,
});
   });
</script>